export const DEMO_ACCOUNTS = {
  farmer: {
    id: "farmer-1",
    name: "Abdul Karim",
    role: "farmer",
    phone: "+880 1712-345678",
    location: "Kumira, Chattogram",
    verified: true,
    avatar: "/bangladeshi-farmer.jpg",
    farmPhoto: "/bangladeshi-farmers-harvesting-fresh-vegetables-in.jpg",
    joinedDate: "2024-10-15",
  },
  buyer: {
    id: "buyer-1",
    name: "Shahed Alam",
    role: "buyer",
    phone: "+880 1812-987654",
    location: "Agrabad, Chattogram",
    businessName: "Shahed's Cafe",
    verified: true,
    avatar: "/bangladeshi-cafe-owner.jpg",
    joinedDate: "2024-11-01",
  },
  admin: {
    id: "admin-1",
    name: "Admin User",
    role: "admin",
    phone: "+880 1912-111222",
    location: "Chattogram",
    avatar: "/admin-user-interface.png",
  },
}

export const DEMO_FARMERS = [
  {
    id: "farmer-1",
    name: "Abdul Karim",
    location: "Kumira, Chattogram",
    verified: true,
    rating: 4.8,
    totalOrders: 156,
    joinedDate: "2024-10-15",
    avatar: "/bangladeshi-farmer.jpg",
  },
  {
    id: "farmer-2",
    name: "Rahim Mia",
    location: "Sitakunda, Chattogram",
    verified: true,
    rating: 4.6,
    totalOrders: 89,
    joinedDate: "2024-11-20",
    avatar: "/farmer-portrait.png",
  },
  {
    id: "farmer-3",
    name: "Fatema Begum",
    location: "Anwara, Chattogram",
    verified: false,
    rating: 4.9,
    totalOrders: 45,
    joinedDate: "2025-01-05",
    avatar: "/female-farmer.png",
  },
]

export const DEMO_PRODUCTS = [
  {
    id: "prod-1",
    farmerId: "farmer-1",
    farmerName: "Abdul Karim",
    name: "Fresh Tomatoes",
    category: "Vegetables",
    pricePerKg: 45,
    availableKg: 25,
    freshness: "Harvested today",
    origin: "Kumira",
    verified: true,
    image: "/red-onions.jpg",
    addedAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    farmerId: "farmer-1",
    farmerName: "Abdul Karim",
    name: "Green Cucumbers",
    category: "Vegetables",
    pricePerKg: 35,
    availableKg: 18,
    freshness: "Harvested today",
    origin: "Kumira",
    verified: true,
    image: "/fresh-green-cucumbers.jpg",
    addedAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    farmerId: "farmer-2",
    farmerName: "Rahim Mia",
    name: "Red Onions",
    category: "Vegetables",
    pricePerKg: 40,
    availableKg: 30,
    freshness: "Harvested today",
    origin: "Sitakunda",
    verified: true,
    image: "/red-onions.jpg",
    addedAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    farmerId: "farmer-2",
    farmerName: "Rahim Mia",
    name: "Fresh Spinach",
    category: "Leafy Greens",
    pricePerKg: 30,
    availableKg: 12,
    freshness: "Harvested today",
    origin: "Sitakunda",
    verified: true,
    image: "/fresh-spinach.png",
    addedAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    farmerId: "farmer-3",
    farmerName: "Fatema Begum",
    name: "Eggplant",
    category: "Vegetables",
    pricePerKg: 38,
    availableKg: 20,
    freshness: "Harvested today",
    origin: "Anwara",
    verified: false,
    image: "/fresh-eggplant.jpg",
    addedAt: new Date().toISOString(),
  },
  {
    id: "prod-6",
    farmerId: "farmer-1",
    farmerName: "Abdul Karim",
    name: "Green Chili",
    category: "Vegetables",
    pricePerKg: 60,
    availableKg: 8,
    freshness: "Harvested today",
    origin: "Kumira",
    verified: true,
    image: "/green-chili-peppers.jpg",
    addedAt: new Date().toISOString(),
  },
]

export const DEMO_ORDERS = [
  {
    id: "order-1",
    buyerId: "buyer-1",
    buyerName: "Shahed Alam",
    farmerId: "farmer-1",
    farmerName: "Abdul Karim",
    items: [
      { productId: "prod-1", name: "Fresh Tomatoes", qty: 5, pricePerKg: 45 },
      { productId: "prod-2", name: "Green Cucumbers", qty: 3, pricePerKg: 35 },
    ],
    totalAmount: 330,
    status: "pending",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 mins ago
    deliveryAddress: "Agrabad, Chattogram",
    note: "Please deliver before 2 PM",
  },
  {
    id: "order-2",
    buyerId: "buyer-1",
    buyerName: "Shahed Alam",
    farmerId: "farmer-2",
    farmerName: "Rahim Mia",
    items: [
      { productId: "prod-3", name: "Red Onions", qty: 10, pricePerKg: 40 },
    ],
    totalAmount: 400,
    status: "accepted",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    acceptedAt: new Date(Date.now() - 1000 * 60 * 60 * 1.5).toISOString(),
    deliveryAddress: "Agrabad, Chattogram",
  },
  {
    id: "order-3",
    buyerId: "buyer-1",
    buyerName: "Shahed Alam",
    farmerId: "farmer-1",
    farmerName: "Abdul Karim",
    items: [
      { productId: "prod-1", name: "Fresh Tomatoes", qty: 8, pricePerKg: 45 },
    ],
    totalAmount: 360,
    status: "delivered",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    acceptedAt: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
    deliveredAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    deliveryAddress: "Agrabad, Chattogram",
  },
]

export const DEMO_NOTIFICATIONS = [
  {
    id: "notif-1",
    userId: "farmer-1",
    type: "new_order",
    title: "New order received",
    message: "Shahed Alam ordered 2 items",
    orderId: "order-1",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "notif-2",
    userId: "buyer-1",
    type: "order_accepted",
    title: "Order accepted",
    message: "Rahim Mia accepted your order",
    orderId: "order-2",
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1.5).toISOString(),
  },
]

export const DEMO_EARNINGS = {
  "farmer-1": {
    today: 690,
    week: 4250,
    month: 18900,
    total: 45600,
  },
  "farmer-2": {
    today: 400,
    week: 2800,
    month: 12400,
    total: 28900,
  },
}

export const DEMO_STATS = {
  admin: {
    totalFarmers: 156,
    verifiedFarmers: 142,
    pendingVerifications: 14,
    totalBuyers: 89,
    activeOrders: 23,
    completedToday: 45,
    totalRevenue: 125000,
    avgDeliveryTime: 2.5, // hours
  },
}
